
namespace MFW.LALLib
{
    public enum ICEStatusEnum
    {
        PLCM_MFW_ICE_STATUS_IDLE
        , PLCM_MFW_ICE_STATUS_FAIL_CONN_TURN
        , PLCM_MFW_ICE_STATUS_FAIL_CONNECTIVITY_CHECK
        , PLCM_MFW_ICE_STATUS_FAIL_TOKEN_AUTHENTICATION_WITH_TURN
        , PLCM_MFW_ICE_STATUS_FAIL_ALLOCATION_TIMEOUT
        , PLCM_MFW_ICE_STATUS_FAIL_CONN_TURN_BY_PROXY
        , PLCM_MFW_ICE_STATUS_FAIL_ACTIVE_NODE_DOWN
    }
}
